version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: C:\Users\HARSHIT\OneDrive\Desktop\CODE WORLD\AI CHATBOT\backend\app\App\Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend/app:/app
    command: python -m  .main

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
